version: "3.9"

services:
  proloquium:
    image: proloquium
    build:
      context: ./python/
      dockerfile: ./Dockerfile
    environment:
      HELLO: WORLD
    volumes:
      - ./python:/home/appuser

volumes:
  media: {}
