[tool.black]
line-length = 120
include = '\.py$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
target-version = ['py39']

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
py_version = 39
src_paths = ["src"]
skip = [".gitignore", ".dockerignore"]

[tool.autoflake]
recursive = true
remove-all-unused-imports = true
remove-unused-variables = true
ignore-init-module-imports = true
remove-duplicate-keys = true
expand-star-imports = true
